In [6]:
import numpy as np

In [7]:
a = [10, 11, 12, 13, 14, 15]

In [8]:
n_a = np.array(a)

In [9]:
n_a

array([10, 11, 12, 13, 14, 15])

In [10]:
n_a[0]

10

In [11]:
n_a[1]

11

In [13]:
last_index = len(n_a) - 1

In [14]:
n_a[last_index]

15

In [15]:
n_a[-1]

15

In [16]:
n_a[-2]

14

In [17]:
n_a[0:3]

array([10, 11, 12])

In [18]:
n_a[3:6]

array([13, 14, 15])

In [20]:
n_a[::2]

array([10, 12, 14])

In [21]:
n_a[1::2]

array([11, 13, 15])

In [22]:
n_b = np.array([100, 101, 102, 103, 104, 105])

In [23]:
n_c = np.concatenate([n_a, n_b])

In [24]:
n_c

array([ 10,  11,  12,  13,  14,  15, 100, 101, 102, 103, 104, 105])

In [25]:
np.sum(n_c)

690

In [26]:
np.max(n_c)

105

In [27]:
np.min(n_c)

10

In [28]:
np.average(n_c)

57.5

In [29]:
n_random = np.random.random(10)

In [30]:
n_random

array([0.3537068 , 0.57638696, 0.45153369, 0.89103829, 0.68600016,
       0.02382563, 0.61336068, 0.31769899, 0.75054046, 0.85594112])

In [31]:
np.max(n_random)

0.8910382933259104

In [32]:
np.min(n_random)

0.023825630705722745

In [33]:
np.sort(n_random)

array([0.02382563, 0.31769899, 0.3537068 , 0.45153369, 0.57638696,
       0.61336068, 0.68600016, 0.75054046, 0.85594112, 0.89103829])

In [34]:
np.argsort(n_random)

array([5, 7, 0, 2, 1, 6, 4, 8, 9, 3])

In [35]:
np.sort(n_random)[::-1]

array([0.89103829, 0.85594112, 0.75054046, 0.68600016, 0.61336068,
       0.57638696, 0.45153369, 0.3537068 , 0.31769899, 0.02382563])